# Generated by Django 2.0.5 on 2019-11-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='大类标签')),
            ],
            options={
                'verbose_name': '大类标签',
                'verbose_name_plural': '大类标签',
            },
        ),
        migrations.CreateModel(
            name='LabelSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='子类标签')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='说明')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.LabelClass', verbose_name='父类')),
            ],
            options={
                'verbose_name': '大类标签',
                'verbose_name_plural': '大类标签',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('has_finshed', models.BooleanField(default=False, verbose_name='是否完成')),
            ],
            options={
                'verbose_name': '标注任务',
                'verbose_name_plural': '标注任务',
            },
        ),
    ]
