# Generated by Django 2.0.5 on 2019-11-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelclass',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='task',
            name='has_distribute',
            field=models.BooleanField(default=False, verbose_name='是否分配'),
        ),
    ]
