# Generated by Django 2.0.5 on 2019-11-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20191101_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50, verbose_name='自定义id')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='图片文件')),
                ('txt', models.TextField(verbose_name='文本')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '待标注数据',
                'verbose_name_plural': '待标注数据',
            },
        ),
    ]
