# Generated by Django 2.0.5 on 2019-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_dataitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelsubclass',
            options={'verbose_name': '子类标签', 'verbose_name_plural': '子类标签'},
        ),
    ]
