# Generated by Django 2.0.5 on 2019-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_label_nums',
            field=models.IntegerField(default=3, verbose_name='最大标注数目'),
        ),
    ]
