# Generated by Django 2.0.5 on 2019-11-04 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_max_label_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='标记时间'),
        ),
    ]
