# Generated by Django 2.0.5 on 2019-11-03 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191103_1509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50, verbose_name='自定义id')),
                ('img_name', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片文件')),
                ('txt', models.TextField(verbose_name='文本')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.LabelSubClass', verbose_name='标注结果')),
                ('tagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标注者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '标注记录',
                'verbose_name_plural': '标注记录',
            },
        ),
    ]
