# Generated by Django 2.0.5 on 2019-11-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_labelresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelresult',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='标记时间'),
        ),
    ]
