# Generated by Django 2.0.5 on 2019-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_labelresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelresult',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
